services:
  - type: web
    name: ngx-admin
    env: node
    plan: free
    buildCommand: npm install && npm run build:prod
    startCommand: npx ng serve --host 0.0.0.0 --port 10000
    runtime: node 14
    envVars:
      - key: NODE_OPTIONS
        value: --max_old_space_size=4096